-------------------------------------------------
-- Audit trail. Every state-changing request through the API lands here, plus explicit
-- auth events (login/logout). Read-only from the app's point of view - never updated.
-------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    actor_email   VARCHAR(255),
    actor_name    VARCHAR(255),
    actor_role    VARCHAR(100),
    action        VARCHAR(20)  NOT NULL,
    entity_type   VARCHAR(60),
    entity_id     VARCHAR(60),
    summary       VARCHAR(500),
    http_method   VARCHAR(10),
    path          VARCHAR(255),
    status_code   INT,
    ip_address    VARCHAR(60),
    user_agent    VARCHAR(255),
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs (action);
