-------------------------------------------------
-- Departments: the org grouping a user belongs to (distinct from their ROLE, which is
-- permissions). One department per user; a department holds many users.
-------------------------------------------------
CREATE TABLE IF NOT EXISTS departments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120) NOT NULL,
    code         VARCHAR(30),
    description  VARCHAR(400),
    head_user_id BIGINT,
    is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_departments_name UNIQUE (name)
);

-- Which department a person sits in. NULL = not assigned yet.
ALTER TABLE app_users
    ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES departments (id);
CREATE INDEX IF NOT EXISTS idx_app_users_department ON app_users (department_id);

-- A task carries its own department (defaulted from the assignee, but overridable) so work can
-- be handed to a team before a specific person picks it up.
ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS department_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_tasks_department ON tasks (department_id);

-------------------------------------------------
-- Sensible construction defaults — rename, add or remove from Settings.
-------------------------------------------------
INSERT INTO departments (name, code, description, is_active, created_at, updated_at)
VALUES ('Civil', 'CIV', 'Structural and civil works', TRUE, now(), now()),
       ('Electrical', 'ELE', 'Electrical installation and maintenance', TRUE, now(), now()),
       ('Plumbing', 'PLB', 'Plumbing, drainage and pipelines', TRUE, now(), now()),
       ('Procurement', 'PRC', 'Purchasing, vendors and material sourcing', TRUE, now(), now()),
       ('Accounts', 'ACC', 'Billing, payments and finance', TRUE, now(), now()),
       ('QA / QC', 'QAQC', 'Quality assurance and inspection', TRUE, now(), now()),
       ('Safety', 'SAF', 'Site safety and compliance', TRUE, now(), now()),
       ('Stores', 'STR', 'Warehouse and inventory', TRUE, now(), now())
ON CONFLICT (name) DO NOTHING;
