-------------------------------------------------
-- Vyapar module: billing & accounting (parties, items, invoices, payments).
-- Kept in its own `vyapar_` table namespace so it doesn't collide with the ERP's
-- project/task domain, which has its own notion of "party" and "material".
-------------------------------------------------

-- Customers and suppliers.
CREATE TABLE IF NOT EXISTS vyapar_parties
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200)   NOT NULL,
    party_type      VARCHAR(20)    NOT NULL DEFAULT 'CUSTOMER',
    phone           VARCHAR(30),
    email           VARCHAR(200),
    gstin           VARCHAR(20),
    billing_address VARCHAR(500),
    city            VARCHAR(120),
    -- Positive = they owe us (receivable). Negative = we owe them (payable).
    opening_balance NUMERIC(16, 2) NOT NULL DEFAULT 0,
    is_active       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_parties_type ON vyapar_parties (party_type);

-- Stock / service items.
CREATE TABLE IF NOT EXISTS vyapar_items
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200)   NOT NULL,
    item_code       VARCHAR(60),
    hsn             VARCHAR(30),
    unit            VARCHAR(30)    NOT NULL DEFAULT 'PCS',
    sale_price      NUMERIC(16, 2) NOT NULL DEFAULT 0,
    purchase_price  NUMERIC(16, 2) NOT NULL DEFAULT 0,
    tax_percent     NUMERIC(6, 2)  NOT NULL DEFAULT 0,
    stock_qty       NUMERIC(16, 3) NOT NULL DEFAULT 0,
    low_stock_alert NUMERIC(16, 3) NOT NULL DEFAULT 0,
    is_service      BOOLEAN        NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_items_name ON vyapar_items (name);

-- One table for every document type (sale, purchase, estimate…) — they share a shape.
CREATE TABLE IF NOT EXISTS vyapar_invoices
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type      VARCHAR(30)    NOT NULL DEFAULT 'SALE',
    invoice_no    VARCHAR(60)    NOT NULL,
    party_id      BIGINT         REFERENCES vyapar_parties (id),
    invoice_date  VARCHAR(30),
    due_date      VARCHAR(30),
    sub_total     NUMERIC(16, 2) NOT NULL DEFAULT 0,
    discount      NUMERIC(16, 2) NOT NULL DEFAULT 0,
    tax_amount    NUMERIC(16, 2) NOT NULL DEFAULT 0,
    total         NUMERIC(16, 2) NOT NULL DEFAULT 0,
    paid_amount   NUMERIC(16, 2) NOT NULL DEFAULT 0,
    payment_type  VARCHAR(40)    NOT NULL DEFAULT 'Cash',
    notes         VARCHAR(1000),
    created_by    BIGINT,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_invoices_type ON vyapar_invoices (doc_type);
CREATE INDEX IF NOT EXISTS idx_vyapar_invoices_party ON vyapar_invoices (party_id);

CREATE TABLE IF NOT EXISTS vyapar_invoice_lines
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT         NOT NULL REFERENCES vyapar_invoices (id) ON DELETE CASCADE,
    item_id     BIGINT,
    item_name   VARCHAR(200)   NOT NULL,
    quantity    NUMERIC(16, 3) NOT NULL DEFAULT 1,
    rate        NUMERIC(16, 2) NOT NULL DEFAULT 0,
    tax_percent NUMERIC(6, 2)  NOT NULL DEFAULT 0,
    amount      NUMERIC(16, 2) NOT NULL DEFAULT 0,
    sort_order  INTEGER        NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_lines_invoice ON vyapar_invoice_lines (invoice_id);

-- Money in / money out, optionally settling an invoice.
CREATE TABLE IF NOT EXISTS vyapar_payments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction    VARCHAR(10)    NOT NULL DEFAULT 'IN',
    party_id     BIGINT         REFERENCES vyapar_parties (id),
    invoice_id   BIGINT,
    payment_date VARCHAR(30),
    amount       NUMERIC(16, 2) NOT NULL DEFAULT 0,
    mode         VARCHAR(40)    NOT NULL DEFAULT 'Cash',
    reference    VARCHAR(120),
    notes        VARCHAR(500),
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_payments_party ON vyapar_payments (party_id);

-------------------------------------------------
-- Vyapar is its own permission module.
-------------------------------------------------
INSERT INTO modules (code, name, created_at, updated_at)
VALUES ('VYAPAR', 'Vyapar', now(), now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (module_id, action, created_at, updated_at)
SELECT m.id, a.action, now(), now()
FROM modules m
         CROSS JOIN (VALUES ('VIEW'), ('CREATE'), ('EDIT'), ('DELETE'), ('APPROVE')) AS a (action)
WHERE m.code = 'VYAPAR'
ON CONFLICT (module_id, action) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.module_id = (SELECT id FROM modules WHERE code = 'VYAPAR')
WHERE r.name = 'Super Admin'
ON CONFLICT DO NOTHING;
