-------------------------------------------------
-- Manual stock corrections ("Adjust Item" in Vyapar) — a small audit trail so the item's
-- stock ledger can show adjustments alongside the sales/purchases that move stock.
-------------------------------------------------
CREATE TABLE IF NOT EXISTS vyapar_stock_adjustments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id    BIGINT         NOT NULL REFERENCES vyapar_items (id),
    project_id BIGINT,
    -- ADD or REDUCE.
    mode       VARCHAR(10)    NOT NULL,
    quantity   NUMERIC(16, 3) NOT NULL DEFAULT 0,
    at_price   NUMERIC(16, 2) NOT NULL DEFAULT 0,
    adj_date   VARCHAR(30),
    note       VARCHAR(500),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_stock_adj_item ON vyapar_stock_adjustments (item_id);
