-------------------------------------------------
-- Cash & Bank for Vyapar: bank accounts, the movements against them (which also cover
-- cash-in-hand, where account_id is NULL), cheques and loans. Plus the firm profile that
-- brands every printed / exported document.
--
-- Everything here is personal: rows belong to the user who created them (owner_user_id) and
-- are never visible to anyone else. Balances are derived from vyapar_cash_bank_txns via a
-- single aggregate query rather than being stored, so they can't drift; the covering indexes
-- below keep that aggregate cheap as the ledger grows.
-------------------------------------------------

CREATE TABLE IF NOT EXISTS vyapar_bank_accounts
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id       BIGINT         NOT NULL,
    name                VARCHAR(160)   NOT NULL,
    opening_balance     NUMERIC(16, 2) NOT NULL DEFAULT 0,
    opening_date        VARCHAR(30),
    account_number      VARCHAR(60),
    ifsc                VARCHAR(20),
    bank_name           VARCHAR(160),
    account_holder      VARCHAR(160),
    upi_id              VARCHAR(120),
    print_upi_qr        BOOLEAN        NOT NULL DEFAULT FALSE,
    print_bank_details  BOOLEAN        NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at          TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_bank_accounts_owner ON vyapar_bank_accounts (owner_user_id, is_active);

CREATE TABLE IF NOT EXISTS vyapar_cash_bank_txns
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id  BIGINT         NOT NULL,
    -- NULL means the movement is against cash in hand rather than a bank account.
    account_id     BIGINT REFERENCES vyapar_bank_accounts (id) ON DELETE CASCADE,
    txn_type       VARCHAR(40)    NOT NULL,
    name           VARCHAR(200),
    txn_date       VARCHAR(30),
    amount         NUMERIC(16, 2) NOT NULL DEFAULT 0,
    -- in = money arriving, out = money leaving.
    direction      VARCHAR(4)     NOT NULL,
    note           VARCHAR(500),
    -- Links the two halves of a transfer so they can be shown or reversed together.
    transfer_group VARCHAR(40),
    created_at     TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at     TIMESTAMP(6) WITHOUT TIME ZONE
);
-- Covers both the ledger read (owner + account, newest first) and the balance aggregate.
CREATE INDEX IF NOT EXISTS idx_vyapar_cb_txns_account ON vyapar_cash_bank_txns (owner_user_id, account_id, id DESC);

CREATE TABLE IF NOT EXISTS vyapar_cheques
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT         NOT NULL,
    cheque_no     VARCHAR(60)    NOT NULL,
    party_name    VARCHAR(200),
    invoice_no    VARCHAR(60),
    -- IN = received from a party, OUT = issued to one.
    direction     VARCHAR(4)     NOT NULL DEFAULT 'IN',
    amount        NUMERIC(16, 2) NOT NULL DEFAULT 0,
    cheque_date   VARCHAR(30),
    transfer_date VARCHAR(30),
    status        VARCHAR(20)    NOT NULL DEFAULT 'OPEN',
    account_id    BIGINT REFERENCES vyapar_bank_accounts (id) ON DELETE SET NULL,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_cheques_owner ON vyapar_cheques (owner_user_id, status);

CREATE TABLE IF NOT EXISTS vyapar_loan_accounts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id  BIGINT         NOT NULL,
    name           VARCHAR(160)   NOT NULL,
    lender         VARCHAR(160),
    account_number VARCHAR(60),
    loan_amount    NUMERIC(16, 2) NOT NULL DEFAULT 0,
    balance        NUMERIC(16, 2) NOT NULL DEFAULT 0,
    interest_rate  NUMERIC(8, 3)  NOT NULL DEFAULT 0,
    term_months    INTEGER        NOT NULL DEFAULT 0,
    start_date     VARCHAR(30),
    emi_amount     NUMERIC(16, 2) NOT NULL DEFAULT 0,
    created_at     TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at     TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_vyapar_loans_owner ON vyapar_loan_accounts (owner_user_id);

-------------------------------------------------
-- One firm profile per user. logo_data_url holds a small base64 image; it is only read by the
-- profile endpoint (never joined into list queries) so it can't weigh down the hot paths.
-------------------------------------------------
CREATE TABLE IF NOT EXISTS vyapar_firm_profile
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id  BIGINT       NOT NULL UNIQUE,
    business_name  VARCHAR(200),
    address        VARCHAR(500),
    phone          VARCHAR(40),
    email          VARCHAR(160),
    gstin          VARCHAR(20),
    state          VARCHAR(80),
    logo_data_url  TEXT,
    footer_note    VARCHAR(500),
    created_at     TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at     TIMESTAMP(6) WITHOUT TIME ZONE
);

-------------------------------------------------
-- Vyapar books are scoped by bank account, not by construction project. The old project_id
-- columns stay for the rows already written against them, but nothing reads them any more.
-------------------------------------------------
ALTER TABLE vyapar_parties            ADD COLUMN IF NOT EXISTS bank_account_id BIGINT;
ALTER TABLE vyapar_items              ADD COLUMN IF NOT EXISTS bank_account_id BIGINT;
ALTER TABLE vyapar_invoices           ADD COLUMN IF NOT EXISTS bank_account_id BIGINT;
ALTER TABLE vyapar_payments           ADD COLUMN IF NOT EXISTS bank_account_id BIGINT;
ALTER TABLE vyapar_stock_adjustments  ADD COLUMN IF NOT EXISTS bank_account_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_vyapar_parties_bank  ON vyapar_parties (bank_account_id);
CREATE INDEX IF NOT EXISTS idx_vyapar_items_bank    ON vyapar_items (bank_account_id);
CREATE INDEX IF NOT EXISTS idx_vyapar_invoices_bank ON vyapar_invoices (bank_account_id);
CREATE INDEX IF NOT EXISTS idx_vyapar_payments_bank ON vyapar_payments (bank_account_id);
