-------------------------------------------------
-- Modules: the ERP feature areas (Project, Finance, Warehouse, ...)
-------------------------------------------------
CREATE TABLE IF NOT EXISTS modules
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(50)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_modules_code UNIQUE (code)
);

-------------------------------------------------
-- Permissions: one row per (module, action) pair
-------------------------------------------------
CREATE TABLE IF NOT EXISTS permissions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_id  BIGINT      NOT NULL REFERENCES modules (id),
    action     VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_permissions_module_action UNIQUE (module_id, action)
);

-------------------------------------------------
-- Roles: dynamic, admin-creatable
-------------------------------------------------
CREATE TABLE IF NOT EXISTS roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_system  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_roles_name UNIQUE (name)
);

-------------------------------------------------
-- Role <-> Permission (many-to-many) - this is the dynamic assignment
-------------------------------------------------
CREATE TABLE IF NOT EXISTS role_permissions
(
    role_id       BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-------------------------------------------------
-- App users
-------------------------------------------------
CREATE TABLE IF NOT EXISTS app_users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255) NOT NULL,
    phone_number  VARCHAR(20),
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    role_id       BIGINT       NOT NULL REFERENCES roles (id),
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_app_users_email UNIQUE (email)
);

-------------------------------------------------
-- Refresh tokens (hashed, revocable)
-------------------------------------------------
CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES app_users (id),
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_permissions_module_id ON permissions (module_id);
CREATE INDEX IF NOT EXISTS idx_app_users_role_id ON app_users (role_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
