-------------------------------------------------
-- Tender module: the bidding pipeline (Sorting → Research → Applied → Won/Lost) and EMD register.
-- One row per tender. Dates are stored as strings because the source workbook mixes formats and the
-- UI treats them as opaque; money is DOUBLE PRECISION to match the project module it hands off to.
-------------------------------------------------
CREATE TABLE IF NOT EXISTS tenders
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source                     VARCHAR(20)  NOT NULL DEFAULT 'PORTAL',
    stage                      VARCHAR(20)  NOT NULL DEFAULT 'SORTING',
    status                     VARCHAR(30),
    status_label               VARCHAR(120),
    department                 VARCHAR(300),
    tender_id                  VARCHAR(120) NOT NULL DEFAULT '',
    name_of_work               VARCHAR(2000),
    location                   VARCHAR(300),
    office_address             VARCHAR(1000),
    estimated_cost             DOUBLE PRECISION,
    contract_value             DOUBLE PRECISION,
    variance_pct               DOUBLE PRECISION,
    duration                   VARCHAR(120),
    duration_months            INTEGER,
    deadline                   VARCHAR(30),
    next_follow_up             VARCHAR(30),
    due_date                   VARCHAR(30),
    submission_date            VARCHAR(30),
    hardcopy_due               VARCHAR(30),
    tech_open                  VARCHAR(60),
    price_open                 VARCHAR(60),
    validity                   VARCHAR(60),
    validity_days              INTEGER,
    dlp                        VARCHAR(60),
    opening_date               VARCHAR(30),
    pre_bid_date               VARCHAR(30),
    fee                        DOUBLE PRECISION,
    emd                        DOUBLE PRECISION,
    emd_mode                   VARCHAR(20),
    emd_state                  VARCHAR(20),
    emd_paid_on                VARCHAR(30),
    emd_released_on            VARCHAR(30),
    emd_instrument_no          VARCHAR(120),
    emd_expiry                 VARCHAR(30),
    pq_criteria                VARCHAR(2000),
    class_req                  VARCHAR(200),
    gst                        VARCHAR(120),
    lab_test                   VARCHAR(500),
    price_escalation           VARCHAR(500),
    deposit_details            VARCHAR(1000),
    pre_bid_info               VARCHAR(1000),
    firm                       VARCHAR(200),
    security_type              VARCHAR(20),
    security_amount            DOUBLE PRECISION,
    additional_security_type   VARCHAR(20),
    additional_security_amount DOUBLE PRECISION,
    bg_charges                 DOUBLE PRECISION,
    security_released_on       VARCHAR(30),
    received_status            VARCHAR(120),
    date_of_received           VARCHAR(30),
    price_bid_stage            VARCHAR(120),
    loss_reason                VARCHAR(40),
    loss_reason_label          VARCHAR(200),
    loss_note                  VARCHAR(2000),
    l1_bidder                  VARCHAR(200),
    l1_value                   DOUBLE PRECISION,
    our_rank                   INTEGER,
    gem_category               VARCHAR(200),
    msme_relaxation            VARCHAR(200),
    experience_turnover        VARCHAR(500),
    eligibility_status         VARCHAR(200),
    priority                   VARCHAR(10),
    view_documents             VARCHAR(1000),
    remarks                    VARCHAR(4000),
    custom_fields              TEXT,
    project_id                 BIGINT,
    created_by                 BIGINT,
    created_at                 TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at                 TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_tenders_stage ON tenders (stage);
CREATE INDEX IF NOT EXISTS idx_tenders_source ON tenders (source);
CREATE INDEX IF NOT EXISTS idx_tenders_tender_id ON tenders (tender_id);

-------------------------------------------------
-- Tender is its own permission module.
-------------------------------------------------
INSERT INTO modules (code, name, created_at, updated_at)
VALUES ('TENDER', 'Tender', now(), now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (module_id, action, created_at, updated_at)
SELECT m.id, a.action, now(), now()
FROM modules m
         CROSS JOIN (VALUES ('VIEW'), ('CREATE'), ('EDIT'), ('DELETE'), ('APPROVE')) AS a (action)
WHERE m.code = 'TENDER'
ON CONFLICT (module_id, action) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.module_id = (SELECT id FROM modules WHERE code = 'TENDER')
WHERE r.name = 'Super Admin'
ON CONFLICT DO NOTHING;
