-------------------------------------------------
-- Tender tracker sub-collections: status milestones, documentation, hardcopy dispatch, materials.
-- Runtime-editable step/document lists ride as JSON so the schema is stable as users add columns.
-------------------------------------------------

CREATE TABLE IF NOT EXISTS tender_milestones
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tender_ref      VARCHAR(120),
    name_of_work    VARCHAR(2000),
    work_start_date VARCHAR(30),
    progress        VARCHAR(200),
    steps_json      TEXT,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at      TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_tender_milestones_ref ON tender_milestones (tender_ref);

CREATE TABLE IF NOT EXISTS tender_documents
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tender_ref     VARCHAR(120),
    name_of_work   VARCHAR(2000),
    progress       VARCHAR(200),
    view_documents VARCHAR(1000),
    pairs_json     TEXT,
    ra_bills_json  TEXT,
    created_at     TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at     TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_tender_documents_ref ON tender_documents (tender_ref);

CREATE TABLE IF NOT EXISTS tender_hardcopy
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date          VARCHAR(30),
    name_of_work  VARCHAR(2000),
    tender_ref    VARCHAR(120),
    document_list VARCHAR(2000),
    packed_by     VARCHAR(200),
    dispatch_by   VARCHAR(200),
    tracking_no   VARCHAR(120),
    arrived       VARCHAR(60),
    arrived_date  VARCHAR(30),
    remarks       VARCHAR(1000),
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_tender_hardcopy_ref ON tender_hardcopy (tender_ref);

CREATE TABLE IF NOT EXISTS tender_materials
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party             VARCHAR(300),
    manufacturer_type VARCHAR(200),
    make              VARCHAR(200),
    location          VARCHAR(300),
    contact           VARCHAR(120),
    email             VARCHAR(200),
    created_at        TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at        TIMESTAMP(6) WITHOUT TIME ZONE
);
