-------------------------------------------------
-- V44 — a general multi-level approval framework, plus non-login members.
--
-- Approval was previously single-step and hardcoded per feature: a leave request carried one
-- approver_id and one decision. Real sites need a chain — the site's PM signs off, then HR, then
-- the director — and they need to see who did what and when.
--
-- Two shapes are supported per entity type:
--   EXPLICIT        — an admin configures ordered levels, each naming one or more roles.
--   REPORTING_CHAIN — levels are derived at submit time by walking roles.reports_to_role_id up
--                     from the requester, so the ladder configured in Roles & Access IS the
--                     approval path and nobody has to maintain it twice.
--
-- Levels are SNAPSHOTTED onto each request when it is raised (approval_request_levels). Editing a
-- chain must never silently rewrite the rules an in-flight request was submitted under.
-------------------------------------------------

-- ---- Configuration ----

CREATE TABLE IF NOT EXISTS approval_chains
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- LEAVE_APPLICATION, PURCHASE_ORDER, … see ApprovalEntityType.
    entity_type VARCHAR(60)  NOT NULL UNIQUE,
    -- EXPLICIT | REPORTING_CHAIN
    mode        VARCHAR(20)  NOT NULL DEFAULT 'EXPLICIT',
    -- An unpublished chain is ignored: the entity falls back to its old single-step behaviour.
    published   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS approval_levels
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_id    BIGINT       NOT NULL REFERENCES approval_chains (id) ON DELETE CASCADE,
    level_order INT          NOT NULL,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_approval_level_order UNIQUE (chain_id, level_order)
);

-- Any ONE of a level's roles may approve it; levels themselves are sequential.
CREATE TABLE IF NOT EXISTS approval_level_roles
(
    level_id BIGINT NOT NULL REFERENCES approval_levels (id) ON DELETE CASCADE,
    role_id  BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (level_id, role_id)
);

-- ---- Running approvals ----

CREATE TABLE IF NOT EXISTS approval_requests
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type   VARCHAR(60)  NOT NULL,
    entity_id     BIGINT       NOT NULL,
    requested_by  BIGINT       NOT NULL,
    -- PENDING | APPROVED | REJECTED | CANCELLED
    status        VARCHAR(15)  NOT NULL DEFAULT 'PENDING',
    current_level INT          NOT NULL DEFAULT 1,
    total_levels  INT          NOT NULL DEFAULT 1,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_approval_request_entity UNIQUE (entity_type, entity_id)
);
CREATE INDEX IF NOT EXISTS idx_approval_requests_status ON approval_requests (entity_type, status);
CREATE INDEX IF NOT EXISTS idx_approval_requests_requester ON approval_requests (requested_by);

-- Who may approve each level OF THIS REQUEST, frozen at submit time.
CREATE TABLE IF NOT EXISTS approval_request_levels
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id  BIGINT      NOT NULL REFERENCES approval_requests (id) ON DELETE CASCADE,
    level_order INT         NOT NULL,
    role_id     BIGINT,
    -- Denormalised so the trail still reads correctly after a role is renamed or deleted.
    role_name   VARCHAR(120)
);
CREATE INDEX IF NOT EXISTS idx_approval_request_levels ON approval_request_levels (request_id, level_order);

-- The audit trail the approval sidebar renders. Append-only.
CREATE TABLE IF NOT EXISTS approval_actions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    BIGINT       NOT NULL REFERENCES approval_requests (id) ON DELETE CASCADE,
    level_order   INT,
    actor_user_id BIGINT,
    actor_name    VARCHAR(255),
    actor_role    VARCHAR(120),
    -- SUBMITTED | APPROVED | REJECTED | CANCELLED
    action        VARCHAR(20)  NOT NULL,
    note          TEXT,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_approval_actions_request ON approval_actions (request_id, id);

-- ---- Non-login members ----
--
-- Site labour is on the payroll and needs attendance, leave and a payslip, but has no reason to
-- ever sign in. Forcing an email + password on those records produced fake addresses like
-- "worker3@site.local" purely to satisfy NOT NULL. Credentials are now optional, and enforced in
-- the service layer only for members who actually log in.

ALTER TABLE app_users
    ADD COLUMN IF NOT EXISTS is_login_user BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE app_users
    ALTER COLUMN email DROP NOT NULL;
ALTER TABLE app_users
    ALTER COLUMN password_hash DROP NOT NULL;

-- ---- Seed the approvable entity types ----
--
-- Rows exist unpublished so the settings screen can list every supported type; nothing changes
-- behaviour until an admin publishes one.

INSERT INTO approval_chains (entity_type, mode, published, created_at, updated_at)
VALUES ('LEAVE_APPLICATION', 'REPORTING_CHAIN', FALSE, now(), now()),
       ('TASK_COMPLETION', 'REPORTING_CHAIN', FALSE, now(), now()),
       ('PAYROLL_RUN', 'EXPLICIT', FALSE, now(), now()),
       ('PURCHASE_ORDER', 'EXPLICIT', FALSE, now(), now()),
       ('SALES_INVOICE', 'EXPLICIT', FALSE, now(), now()),
       ('PAYMENT_ENTRY', 'EXPLICIT', FALSE, now(), now()),
       ('SITE_EXPENSE', 'EXPLICIT', FALSE, now(), now()),
       ('MATERIAL_PURCHASE', 'EXPLICIT', FALSE, now(), now()),
       ('TENDER_SUBMISSION', 'EXPLICIT', FALSE, now(), now())
ON CONFLICT (entity_type) DO NOTHING;

-- ---- Permissions ----

INSERT INTO modules (code, name, created_at, updated_at)
VALUES ('APPROVAL', 'Approvals', now(), now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (module_id, action, created_at, updated_at)
SELECT m.id, a.action, now(), now()
FROM modules m
         CROSS JOIN (VALUES ('VIEW'), ('CREATE'), ('EDIT'), ('DELETE'), ('APPROVE')) AS a (action)
WHERE m.code = 'APPROVAL'
ON CONFLICT (module_id, action) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
         JOIN permissions p ON p.module_id = (SELECT id FROM modules WHERE code = 'APPROVAL')
WHERE r.name = 'Super Admin'
ON CONFLICT DO NOTHING;
