-- Procurement: request for quotation, and the quotes that come back against it.
--
-- This is the only part of the buying chain nothing else in the ERP models. Purchase orders,
-- vendors and bills already exist in vyapar_*; procurement stops at the point a vendor is chosen
-- and hands the award over to a Vyapar purchase order.
--
-- Two shapes worth reading before changing anything:
--
--  * A quote is priced PER LINE (`procurement_quote_lines`), not as one figure per vendor. A vendor
--    routinely quotes four of five lines and skips the fifth, and the comparison has to show that
--    as "no quote" rather than as zero — a blank read as free has caused real mistakes.
--  * An award is made PER LINE (`procurement_rfq_lines.awarded_vendor_party_id`). A five-line
--    enquiry commonly splits across three suppliers; one winner per RFQ cannot express that.

CREATE TABLE procurement_rfqs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfq_no       VARCHAR(40)  NOT NULL UNIQUE,
    title        VARCHAR(200) NOT NULL,
    project_id   BIGINT,
    -- Draft | Sent | Responses In | Awarded | Closed
    status       VARCHAR(20)  NOT NULL DEFAULT 'Draft',
    rfq_date     VARCHAR(10),
    -- The window vendors may reply in. Plain dates, matching the rest of the schema.
    due_by       VARCHAR(10),
    notes        TEXT,
    created_by   BIGINT,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6)
);

CREATE TABLE procurement_rfq_lines (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfq_id         BIGINT       NOT NULL REFERENCES procurement_rfqs(id) ON DELETE CASCADE,
    -- Free text, or a Vyapar item when the buyer picked one from the catalogue.
    item_id        BIGINT,
    item_name      VARCHAR(200) NOT NULL,
    unit           VARCHAR(30),
    quantity       NUMERIC(16,3) NOT NULL DEFAULT 1,
    -- The agreed rate from a vendor rate card, where one exists. Quotes are judged against it, so
    -- the screen can say "cheapest, and still above what we agreed" rather than only "cheapest".
    budget_rate    NUMERIC(16,2),
    -- The decision. Null until someone makes it.
    awarded_vendor_party_id BIGINT,
    -- Why this vendor, when it is not the cheapest — the sentence someone asks for months later.
    award_reason   VARCHAR(300),
    sort_order     INT          NOT NULL DEFAULT 0,
    created_at     TIMESTAMP(6),
    updated_at     TIMESTAMP(6)
);

CREATE TABLE procurement_quotes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfq_id          BIGINT NOT NULL REFERENCES procurement_rfqs(id) ON DELETE CASCADE,
    -- The vendor is a Vyapar party. Procurement keeps no vendor list of its own.
    vendor_party_id BIGINT NOT NULL,
    -- Quotes get revised; the comparison says which version it is showing.
    version         INT    NOT NULL DEFAULT 1,
    received_on     VARCHAR(10),
    delivery_days   INT,
    -- Whole-quote terms, applied after the lines are totalled.
    discount        NUMERIC(16,2) NOT NULL DEFAULT 0,
    charges         NUMERIC(16,2) NOT NULL DEFAULT 0,
    tax_percent     NUMERIC(6,2)  NOT NULL DEFAULT 0,
    note            VARCHAR(500),
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    -- One live quote per vendor per enquiry; a revision bumps the version in place.
    CONSTRAINT uq_quote_per_vendor UNIQUE (rfq_id, vendor_party_id)
);

CREATE TABLE procurement_quote_lines (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id     BIGINT NOT NULL REFERENCES procurement_quotes(id) ON DELETE CASCADE,
    rfq_line_id  BIGINT NOT NULL REFERENCES procurement_rfq_lines(id) ON DELETE CASCADE,
    -- NULL means the vendor did not quote this line. Deliberately nullable: 0 would read as free.
    rate         NUMERIC(16,2),
    -- Vendors sometimes quote a different quantity (pack sizes). NULL means "as asked".
    quantity     NUMERIC(16,3),
    note         VARCHAR(300),
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    CONSTRAINT uq_quote_line UNIQUE (quote_id, rfq_line_id)
);

CREATE INDEX idx_proc_rfq_project   ON procurement_rfqs (project_id);
CREATE INDEX idx_proc_rfq_status    ON procurement_rfqs (status);
CREATE INDEX idx_proc_lines_rfq     ON procurement_rfq_lines (rfq_id);
CREATE INDEX idx_proc_quotes_rfq    ON procurement_quotes (rfq_id);
CREATE INDEX idx_proc_qlines_quote  ON procurement_quote_lines (quote_id);
