-- Bring the RFQ up to the field set the client actually works with.
--
-- Taken from their live tool screen by screen: the create dialog, the Bill To / Ship To panel, and
-- the builder page with its material list, target suppliers and terms.
--
-- Three things this adds that the first cut missed entirely:
--
--  * A bidding WINDOW (start and end), not just a reply deadline. Suppliers are told when bidding
--    opens as well as when it shuts.
--  * Bill To and Ship To as addresses on the document. They differ: the bill goes to the Rajkot
--    office, the goods go to a site. An enquiry that cannot say where to deliver is not sendable.
--  * TARGET SUPPLIERS — who was invited, which is not the same as who replied. Without it there is
--    no way to show "5 invited, 2 responded", chase the silent three, or resend.

ALTER TABLE procurement_rfqs ADD COLUMN tax_type VARCHAR(10) NOT NULL DEFAULT 'ITEM';
COMMENT ON COLUMN procurement_rfqs.tax_type IS 'ITEM = tax per line, BILL = one rate on the whole bill';

ALTER TABLE procurement_rfqs ADD COLUMN bidding_start_date VARCHAR(10);
ALTER TABLE procurement_rfqs ADD COLUMN bidding_end_date   VARCHAR(10);
ALTER TABLE procurement_rfqs ADD COLUMN delivery_date      VARCHAR(10);
ALTER TABLE procurement_rfqs ADD COLUMN terms              TEXT;

-- The reply deadline we already had is the end of the bidding window under a plainer name.
UPDATE procurement_rfqs SET bidding_end_date = due_by WHERE due_by IS NOT NULL;

-- Bill To / Ship To, held on the document rather than looked up live: an address printed on an
-- enquiry sent in August must still read the same next year, even if the firm moves.
ALTER TABLE procurement_rfqs ADD COLUMN bill_to_name    VARCHAR(200);
ALTER TABLE procurement_rfqs ADD COLUMN bill_to_address TEXT;
ALTER TABLE procurement_rfqs ADD COLUMN bill_to_gstin   VARCHAR(20);
ALTER TABLE procurement_rfqs ADD COLUMN ship_to_name    VARCHAR(200);
ALTER TABLE procurement_rfqs ADD COLUMN ship_to_address TEXT;
ALTER TABLE procurement_rfqs ADD COLUMN ship_to_gstin   VARCHAR(20);
ALTER TABLE procurement_rfqs ADD COLUMN ship_same_as_bill BOOLEAN NOT NULL DEFAULT FALSE;

-- Per line: the HSN code the supplier needs to quote tax, and a delivery date that can differ from
-- the document's — valves next week, the pipe that follows them next month.
ALTER TABLE procurement_rfq_lines ADD COLUMN hsn_code      VARCHAR(20);
ALTER TABLE procurement_rfq_lines ADD COLUMN delivery_date VARCHAR(10);
-- The brand/spec sub-line their enquiries carry under the item name ("Kirloskar, IVI, GM").
ALTER TABLE procurement_rfq_lines ADD COLUMN specification VARCHAR(500);

-- Who was invited. Separate from who quoted, so an enquiry can report "5 invited, 2 responded".
CREATE TABLE procurement_rfq_suppliers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfq_id          BIGINT NOT NULL REFERENCES procurement_rfqs(id) ON DELETE CASCADE,
    vendor_party_id BIGINT NOT NULL,
    -- Stamped when the enquiry is actually sent, so "invited but never sent" stays visible.
    sent_at         TIMESTAMP(6),
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT uq_rfq_supplier UNIQUE (rfq_id, vendor_party_id)
);

CREATE INDEX idx_proc_rfq_suppliers ON procurement_rfq_suppliers (rfq_id);

-- Anyone who has already quoted was obviously invited; backfill so counts are right from day one.
INSERT INTO procurement_rfq_suppliers (rfq_id, vendor_party_id, created_at, updated_at)
SELECT DISTINCT q.rfq_id, q.vendor_party_id, now(), now()
  FROM procurement_quotes q
 WHERE NOT EXISTS (
   SELECT 1 FROM procurement_rfq_suppliers s
    WHERE s.rfq_id = q.rfq_id AND s.vendor_party_id = q.vendor_party_id);
