-------------------------------------------------
-- Project master data. Columns mirror ProjectEntity (ddl-auto: validate),
-- so types/names must stay in sync with project-service ProjectEntity.
-- Idempotent (IF NOT EXISTS / ON CONFLICT) so it is safe to (re)apply.
-------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code       VARCHAR(50) UNIQUE,
    name               VARCHAR(200)  NOT NULL,
    category           VARCHAR(200),
    stage              VARCHAR(100),
    status             VARCHAR(20)   NOT NULL DEFAULT 'NOT_STARTED',
    health             VARCHAR(20)   NOT NULL DEFAULT 'HEALTHY',
    customer_name      VARCHAR(200),
    key_personnel      VARCHAR(200),
    address            VARCHAR(500),
    city               VARCHAR(100),
    company_branch     VARCHAR(200),
    start_date         VARCHAR(30),
    end_date           VARCHAR(30),
    progress           INT              NOT NULL DEFAULT 0,
    attendance_radius  INT              NOT NULL DEFAULT 500,
    project_value      DOUBLE PRECISION NOT NULL DEFAULT 0,
    orientation        VARCHAR(100),
    dimension          VARCHAR(100),
    scope_of_work      VARCHAR(2000),
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_projects_status ON projects (status);

-- Seed real Hi-Tech Construction projects (idempotent on project_code).
INSERT INTO projects (project_code, name, category, stage, status, health, customer_name, address, city, start_date, end_date, progress, project_value, created_at, updated_at)
VALUES
 ('HT-2026-001', 'Construction of CC Road', 'Directorate Urban Administration and Development', 'Received LOA', 'NOT_STARTED', 'HEALTHY', 'Directorate Urban Admin & Development', NULL, NULL, NULL, NULL, 0, 12500000, now(), now()),
 ('HT-2026-002', 'HI-TECH OFFICE', 'Internal', 'Fit-out', 'ONGOING', 'HEALTHY', 'Hi-Tech Construction', 'Rajkot', 'Rajkot', '01-Apr-2026', '30-Sep-2026', 45, 3500000, now(), now()),
 ('HT-2026-003', 'Ishwariya (Gram Panchayat) Amreli', 'Road and Building Division', 'Pending For Land Clearance', 'ONGOING', 'AT_RISK', 'Amreli Gram Panchayat', 'Village Ishwariya, Tal. Kunkavav, Amreli', 'Amreli', '13-Jan-2026', '13-Jul-2026', 20, 8600000, now(), now()),
 ('HT-2026-004', 'Jetpur (Fire System)', 'Fire & Safety', 'Completed', 'COMPLETED', 'AT_RISK', 'Jetpur Nagarpalika', 'Jetpur', 'Jetpur', '22-Oct-2024', '22-Nov-2024', 100, 1500000, now(), now()),
 ('HT-2026-005', 'Lakhapadar (Gram Panchayat) Amreli', 'Road and Building Division', 'Pending For Land Clearance', 'ONGOING', 'AT_RISK', 'Amreli Gram Panchayat', 'Village Lakhapadar, Ta. Kunkavav, Amreli', 'Amreli', '13-Jan-2026', '13-Jul-2026', 18, 7900000, now(), now()),
 ('HT-2026-006', 'Mayapadar (Gram Panchayat) Amreli', 'Road and Building Division', 'Pending For Land Clearance', 'ONGOING', 'AT_RISK', 'Amreli Gram Panchayat', 'Village Mayapadar, Tal. Kunkavav, Amreli', 'Amreli', '13-Jan-2026', '13-Jul-2026', 22, 8100000, now(), now()),
 ('HT-2026-007', 'Morvada (Gram Panchayat) Amreli', 'Road and Building Division', 'Pending For Land Clearance', 'ONGOING', 'AT_RISK', 'Amreli Gram Panchayat', 'Village Morvada, Tal. Kunkavav, Amreli', 'Amreli', '13-Jan-2026', '13-Jul-2026', 15, 7600000, now(), now()),
 ('HT-2026-008', 'Navagam (D.I. Pipeline)', 'Water Supply', NULL, 'COMPLETED', 'HEALTHY', 'Gujarat Water Supply Board', NULL, NULL, NULL, NULL, 100, 5400000, now(), now()),
 ('HT-2026-009', 'New Jagnathplot (D.I. Pipeline)', 'Water Supply', NULL, 'COMPLETED', 'HEALTHY', 'Rajkot Municipal Corporation', NULL, 'Rajkot', '17-Feb-2025', NULL, 100, 4800000, now(), now()),
 ('HT-2026-010', 'Old Jagnathplot (D.I. Pipeline)', 'Water Supply', NULL, 'ONHOLD', 'AT_RISK', 'Rajkot Municipal Corporation', NULL, 'Rajkot', '17-Feb-2025', '17-Dec-2026', 35, 4200000, now(), now()),
 ('HT-2026-011', 'Pedak Road (D.I. Pipeline)', 'Rajkot Municipal Corporation', 'Final Bill In Progress', 'COMPLETED', 'AT_RISK', 'Rajkot Municipal Corporation', 'Pedak Road, Rajkot', 'Rajkot', '24-Feb-2025', '23-Mar-2026', 100, 9300000, now(), now()),
 ('HT-2026-012', 'Raydi (Animal Husbandary EPI Center)', 'Road and Building Division', 'Sample Testing At GERI', 'ONGOING', 'AT_RISK', 'Dept. of Animal Husbandry', 'Village Rayadi, Ta. Jamkandorana, Rajkot', 'Rajkot', '02-Jan-2026', '02-Jul-2026', 30, 6700000, now(), now()),
 ('HT-2026-013', 'RMC D.I. Pipeline - Phase 1', 'Rajkot Municipal Corporation', 'Execution', 'ONGOING', 'AT_RISK', 'Rajkot Municipal Corporation', 'Rajkot', 'Rajkot', '05-Mar-2026', '05-Dec-2026', 55, 11200000, now(), now()),
 ('HT-2026-014', 'RMC D.I. Pipeline - Phase 2', 'Rajkot Municipal Corporation', 'Execution', 'ONGOING', 'HEALTHY', 'Rajkot Municipal Corporation', 'Rajkot', 'Rajkot', '05-Mar-2026', '05-Feb-2027', 60, 10800000, now(), now()),
 ('HT-2026-015', 'RMC D.I. Pipeline - Phase 3', 'Rajkot Municipal Corporation', 'Execution', 'ONGOING', 'HEALTHY', 'Rajkot Municipal Corporation', 'Rajkot', 'Rajkot', '05-Apr-2026', '05-Mar-2027', 40, 10500000, now(), now()),
 ('HT-2026-016', 'Vanthali (Gram Panchayat) at Junagadh', 'Road and Building Division', 'Received LOA', 'NOT_STARTED', 'HEALTHY', 'Vanthali Gram Panchayat', 'Ta. Vanthali, Junagadh', 'Junagadh', NULL, NULL, 0, 6900000, now(), now()),
 ('HT-2026-017', 'Trambakpur (Gram Panchayat) Amreli', 'Road and Building Division', 'Received LOA', 'NOT_STARTED', 'HEALTHY', 'Trambakpur Gram Panchayat', 'Amreli', 'Amreli', NULL, NULL, 0, 5600000, now(), now()),
 ('HT-2026-018', 'Vavdi Road Widening', 'Road and Building Division', 'Tender', 'NOT_STARTED', 'HEALTHY', 'Rajkot Municipal Corporation', 'Vavdi, Rajkot', 'Rajkot', NULL, NULL, 0, 8800000, now(), now()),
 ('HT-2026-019', 'Wankaner Water Supply Scheme', 'Water Supply', NULL, 'COMPLETED', 'HEALTHY', 'GWSSB', 'Wankaner', 'Wankaner', NULL, NULL, 100, 7200000, now(), now())
ON CONFLICT (project_code) DO NOTHING;
