-- Work orders: the labour half of procurement.
--
-- An RFQ buys material from a supplier. A work order buys *work* from a subcontractor — plastering,
-- fabrication, pipe laying — and the client runs 22 of them live. It is the same shape as an award
-- (a party, priced lines, a total that ends in a Vyapar bill) with three differences that matter:
--
--  * **Quantity is measured, not counted.** A site clerk writes 4 x 12.5 x 0.6 x 0.15 and the
--    quantity falls out of it. Storing the four numbers rather than only their product is what lets
--    a disputed bill be re-checked six months later against what was actually measured.
--  * **It is billed in instalments.** A ₹7,10,000 subcontract is paid across many running bills, so
--    "what is still owed on this order" is a question only this table can answer.
--  * **We issue him material.** Cement and steel go out of our store against his order and come off
--    his bill, so the issue has to hang off the work order rather than float in the warehouse.
--
-- Milestones are deliberately not modelled. The tool the client already pays for has the column,
-- the tab and the button — and all 22 of their live orders read 0 / 0. Building dependency graphs
-- and per-milestone invoicing to match a feature nobody has ever used is how a module gets big
-- without getting useful. The list still shows a milestone column, fed by item progress.

CREATE TABLE procurement_work_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wo_no           VARCHAR(40)  NOT NULL UNIQUE,
    title           VARCHAR(200) NOT NULL,
    project_id      BIGINT,
    -- The subcontractor is a Vyapar party, like every other vendor. No second party list.
    vendor_party_id BIGINT       NOT NULL,
    -- Draft | Approved | In Progress | Completed | Closed
    status          VARCHAR(20)  NOT NULL DEFAULT 'Draft',
    wo_date         VARCHAR(10),
    start_date      VARCHAR(10),
    end_date        VARCHAR(10),
    -- Whole-order terms, applied after the items are totalled.
    tax_percent     NUMERIC(6,2)  NOT NULL DEFAULT 0,
    discount        NUMERIC(16,2) NOT NULL DEFAULT 0,
    charges         NUMERIC(16,2) NOT NULL DEFAULT 0,
    -- Where he is paid. Held on the order because a subcontractor's account is agreed with the
    -- order, and the accounts clerk raising the payment should not have to go hunting for it.
    bank_account_name   VARCHAR(120),
    bank_account_number VARCHAR(40),
    bank_ifsc           VARCHAR(20),
    terms           TEXT,
    notes           TEXT,
    created_by      BIGINT,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6)
);

CREATE INDEX idx_proc_wo_project ON procurement_work_orders (project_id);
CREATE INDEX idx_proc_wo_vendor  ON procurement_work_orders (vendor_party_id);

CREATE TABLE procurement_work_order_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id   BIGINT       NOT NULL REFERENCES procurement_work_orders(id) ON DELETE CASCADE,
    -- Free text, or a Vyapar item when one was picked from the catalogue.
    item_id         BIGINT,
    item_name       VARCHAR(200) NOT NULL,
    description     VARCHAR(300),
    unit            VARCHAR(30),
    -- N x L x W x H. All four are optional: half of site work is quoted per running metre with no
    -- dimensions at all, and forcing a 1 into every box would turn a blank into a false measurement.
    dim_n           NUMERIC(16,3),
    dim_l           NUMERIC(16,3),
    dim_w           NUMERIC(16,3),
    dim_h           NUMERIC(16,3),
    -- The quantity actually ordered. Derived from the dimensions when they are given, typed when
    -- they are not; stored either way so the figure the order was signed on cannot drift.
    quantity        NUMERIC(16,3) NOT NULL DEFAULT 1,
    rate            NUMERIC(16,2) NOT NULL DEFAULT 0,
    -- How much of this line is physically done. Progress lives on the line, not the order: a
    -- subcontract is routinely 90% laid and 0% tested, and one number for the order hides that.
    progress_percent NUMERIC(6,2) NOT NULL DEFAULT 0,
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6)
);

CREATE INDEX idx_proc_wo_items_wo ON procurement_work_order_items (work_order_id);

-- A running bill against the order. Many per work order.
CREATE TABLE procurement_subcon_bills (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id   BIGINT        NOT NULL REFERENCES procurement_work_orders(id) ON DELETE CASCADE,
    bill_no         VARCHAR(40),
    bill_date       VARCHAR(10),
    amount          NUMERIC(16,2) NOT NULL DEFAULT 0,
    -- Deducted on the face of the bill: retention held back, and the value of material we issued
    -- him. Both are recovered from what he is paid, so they belong on the bill, not in a note.
    retention       NUMERIC(16,2) NOT NULL DEFAULT 0,
    material_recovery NUMERIC(16,2) NOT NULL DEFAULT 0,
    note            VARCHAR(500),
    -- The Vyapar purchase bill this became, once it was actually booked. Null while it is only
    -- recorded here — procurement tracks the subcontract, Vyapar keeps the books.
    vyapar_invoice_id BIGINT,
    created_by      BIGINT,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6)
);

CREATE INDEX idx_proc_subcon_bills_wo ON procurement_subcon_bills (work_order_id);

-- Material issued to the subcontractor against this order, and anything he sends back.
CREATE TABLE procurement_subcon_materials (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id   BIGINT        NOT NULL REFERENCES procurement_work_orders(id) ON DELETE CASCADE,
    item_id         BIGINT,
    item_name       VARCHAR(200)  NOT NULL,
    unit            VARCHAR(30),
    -- ISSUE = out to him, RETURN = back to us, CONSUMED = used up on the work.
    -- Kept as movements rather than a running balance so "he still holds 40 bags" is arrived at
    -- from records that each have a date and a person behind them.
    movement        VARCHAR(12)   NOT NULL DEFAULT 'ISSUE',
    quantity        NUMERIC(16,3) NOT NULL DEFAULT 0,
    -- What it is recovered at. Zero means free issue — common, and different from unpriced.
    rate            NUMERIC(16,2) NOT NULL DEFAULT 0,
    moved_on        VARCHAR(10),
    note            VARCHAR(300),
    created_by      BIGINT,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6)
);

CREATE INDEX idx_proc_subcon_mat_wo ON procurement_subcon_materials (work_order_id);
