-------------------------------------------------
-- Project location structure (Block → Floor → Unit …). Self-referential tree
-- scoped to a project. Mirrors ProjectLocationEntity (ddl-auto: validate).
-- Deleting a node cascades to its sub-locations.
-------------------------------------------------
CREATE TABLE IF NOT EXISTS project_locations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT      NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    parent_id   BIGINT      REFERENCES project_locations(id) ON DELETE CASCADE,
    name        VARCHAR(200) NOT NULL,
    sort_order  INT         NOT NULL DEFAULT 0,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_project_locations_project ON project_locations (project_id);
CREATE INDEX IF NOT EXISTS idx_project_locations_parent  ON project_locations (parent_id);
