-------------------------------------------------
-- Project members: who can access a project. Drives per-user project/task visibility.
-------------------------------------------------
CREATE TABLE IF NOT EXISTS project_members
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT uq_project_members UNIQUE (project_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_project_members_user ON project_members (user_id);
CREATE INDEX IF NOT EXISTS idx_project_members_project ON project_members (project_id);

-------------------------------------------------
-- Tasks (Taskopad)
-------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_code   VARCHAR(40)  NOT NULL,
    title       VARCHAR(300) NOT NULL,
    description TEXT,
    project_id  BIGINT,
    assignee_id BIGINT       NOT NULL,
    created_by  BIGINT,
    client_name VARCHAR(200),
    status      VARCHAR(20)  NOT NULL,
    priority    VARCHAR(20)  NOT NULL,
    progress    INTEGER      NOT NULL DEFAULT 0,
    due_date    VARCHAR(30),
    is_draft    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks (project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks (assignee_id);

-------------------------------------------------
-- Task followers (element collection)
-------------------------------------------------
CREATE TABLE IF NOT EXISTS task_followers
(
    task_id BIGINT NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (task_id, user_id)
);

-------------------------------------------------
-- Subtasks
-------------------------------------------------
CREATE TABLE IF NOT EXISTS task_subtasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT       NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    title       VARCHAR(500) NOT NULL,
    done        BOOLEAN      NOT NULL DEFAULT FALSE,
    assignee_id BIGINT,
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_task_subtasks_task ON task_subtasks (task_id);

-------------------------------------------------
-- Comments
-------------------------------------------------
CREATE TABLE IF NOT EXISTS task_comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT        NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    author_id  BIGINT        NOT NULL,
    text       VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_task_comments_task ON task_comments (task_id);

-------------------------------------------------
-- Attachments (metadata + optional inlined data URL)
-------------------------------------------------
CREATE TABLE IF NOT EXISTS task_attachments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      BIGINT       NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    uploaded_by  BIGINT       NOT NULL,
    name         VARCHAR(300) NOT NULL,
    size_label   VARCHAR(40),
    content_type VARCHAR(120),
    data_url     TEXT,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_task_attachments_task ON task_attachments (task_id);

-------------------------------------------------
-- Activity log (append-only)
-------------------------------------------------
CREATE TABLE IF NOT EXISTS task_activity
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id    BIGINT       NOT NULL REFERENCES tasks (id) ON DELETE CASCADE,
    actor_id   BIGINT,
    text       VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_task_activity_task ON task_activity (task_id);
